- hosts: all
  become: true
  gather_facts: yes  # This is necessary to collect the details about the operating system

  tasks:
    - include_tasks: ansible/zsh.yaml
    - include_tasks: ansible/nvim-setup.yaml
    - include_tasks: ansible/node.yaml
    - include_tasks: ansible/brave.yaml
    - include_tasks: ansible/core.yaml
    - include_tasks: ansible/git-setup.yaml
    - include_tasks: ansible/node.yaml
    - include_tasks: ansible/productivity.yaml
    - include_tasks: ansible/slack.yaml
    - include_tasks: ansible/zsh.yaml
