- hosts: all
  become: true
  gather_facts: yes  # This is necessary to collect the details about the operating system

  tasks:
    - name: Install Zsh on Linux
      package:
        name: zsh
        state: present
      tags:
      - zsh 
      when: ansible_facts['os_family'] != "Windows"  # Only runs on non-Windows systems

    - name: Change shell to Zsh
      shell: chsh -s `which zsh`
      tags:
      - zsh 
      when: ansible_facts['os_family'] != "Windows"  # Only runs on non-Windows systems

    - name: Install OhMyZsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags:
      - zsh 
      when: ansible_facts['os_family'] != "Windows"  # Only runs on non-Windows systems

    - name: Install zsh-autosuggestions plugin
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
      tags:
      - zsh 
      when: ansible_facts['os_family'] != "Windows"  # Only runs on non-Windows systems

    - name: Update .zshrc to include plugin
      ansible.builtin.lineinfile:
        path: ~/.zshrc
        line: 'plugins=(git zsh-autosuggestions)'
        regexp: '^plugins=\(.*\)$'
        backrefs: yes
      tags:
      - zsh 
      when: ansible_facts['os_family'] != "Windows"  # Only runs on non-Windows systems

    - name: Install Zsh and OhMyZsh in WSL
      win_shell: |
        wsl --distribution Ubuntu --user root --exec sh -c "apt update && apt install zsh -y && sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\" && chsh -s `which zsh`"
      when: ansible_facts['os_family'] == "Windows"
    
